name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug  # Change to "Release" if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3 and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Install Conan
      run: |
        pip3 install conan

    - name: Detect and create Conan default profile
      run: |
        conan profile detect  # Automatically creates the default profile

    - name: Install dependencies with Conan
      run: |
        conan install . -s build_type=${{env.BUILD_TYPE}} --build=missing

    - name: Configure CMake with Conan preset
      run: |
        cmake --preset conan-${{env.BUILD_TYPE}}

    - name: Build the project
      run: |
        cmake --build --preset conan-${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: |
        echo "Running tests..."
        ctest -C ${{env.BUILD_TYPE}}
      continue-on-error: false
